### ISSUE TITLE
Changing the name for the advancement

### ISSUE THREAD

**Issue by DiamondJMS** [davidjjung/peepingangels#1]
I know how to make a resource pack for changing the advancement name, I can make one and send it or tell you how to make it.
Also sorry if this is not the right place, I've never used this feature

**Comment by davidjjung** [comment]
Hey! As it turns out, I actually did implement the resource pack but forgot to clean up the mod description. Thanks for going to the trouble though :] I'll correct the mod desc as needed, thank you for the reminder
